In [ ]:
ara = [1, 'a', 'Jihad']
print(ara[0], ara[2])
# that means array can hold multiple data types, and it is dynamic in nature

1 Jihad


In [ ]:
list = [1,6,7,8,9]

list.append(50) #add new value
print(list)

list.insert(1,-9) # add value at certain index
print(list)

list.remove(-9) # here we must ensure that -9 is present in list, else it will throw an error
print(list)

poppedVal = list.pop(2) # pop by index
print(poppedVal, list)

list[0] = -9
print(list)

for idx,item in enumerate(list): # traverse through list
  print(idx,'->',item)

[1, 6, 7, 8, 9, 50]
[1, -9, 6, 7, 8, 9, 50]
[1, 6, 7, 8, 9, 50]
7 [1, 6, 8, 9, 50]
[-9, 6, 8, 9, 50]
0 -> -9
1 -> 6
2 -> 8
3 -> 9
4 -> 50


In [47]:
# NumPy arrays are:
# fast
# memory-efficient
# vectorized (operations happen in bulk)
# mathematical (matrix operations)

import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr)

print(arr.shape)
print(arr.size)
print(arr.dtype)

print(arr/2)

slicedArray = arr[1:3] # array slicing, this line only copy the items, the array remains as it is
print(slicedArray)

reshappedArray = arr.reshape(3,2) # this line convert this array into 3*2 matrix
print(reshappedArray)

[1 2 3 4 5 6]
(6,)
6
int64
[0.5 1.  1.5 2.  2.5 3. ]
[2 3]
[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# statistical method, useful for ML (we must use numpy array)

arr = np.array([1,2,3,4,5])
print(arr.sum())
print(arr.mean())
print(arr.min())
print(arr.max())
print(np.median(arr))
print(np.std(arr)) #standerd deviation

15
3.0
1
5
3.0
1.4142135623730951


In [ ]:
import numpy as np

_2DArray = np.zeros((3,3)) # this will create an 3x3 array initialized with 0 
                           # similarly if we write np.ones((m,n)), it will initialized with 1
print('2D array with np :\n',_2DArray)

_1Drange = np.arange(0,10,2) # (start, end, step) including start, excluding end, executing step
print('1D array with np :\n',_1Drange)

linespaceArray = np.linspace(1,5,10) # (start, end, quantity) will generate an 1D array of 'quantity' times number between start(include) and end(include)
# this might be useful for sampling purpose
print('Line space :\n',linespaceArray)


randomFloatList = np.random.rand(3,3) # provide 3x3 list of float number from 0->1
print('Randon Float number List : \n', randomFloatList)

randomIntList = np.random.randint(1,100,5) # (start, end, quantity) start->inclusive, end->exclusive, quantity-> how much number to create
print(randomIntList)

2D array with np :
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
1D array with np :
 [0 2 4 6 8]
Line space :
 [1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
Randon Float number List : 
 [[1.17598243e-01 9.96419020e-01 1.00509201e-01]
 [6.94775194e-02 5.68024816e-04 4.59336810e-01]
 [6.88219215e-01 1.44882499e-01 1.80333588e-01]]
[47 96 42  8 45]


| Feature   | List  | array module | NumPy array       |
| --------- | ----- | ------------ | ----------------- |
| Speed     | Slow  | Medium       | Fastest           |
| Data type | Mixed | Single type  | Single type       |
| Math ops  | No    | Limited      | Yes (vectorized)  |
| ML usage  | No    | No           | ✔ Yes             |
| Dimension | Any   | 1D           | Multi-dimensional |
